```{r}
x <- NULL
IS.null(x)
is.null(x)
y <- 100
x + y
y
a <- 100
b <- 90
c <- NA;
a+b
a+b+y
x+c
x+y
z <- NA
y+z
y
y+z
c
c+z
1 + 2
100 - 99
2 * 3
100 / 2
100 %/% 3
100 / 3
10^2
10**2
5 > 3
5 >= 5
2 < 5
2 <= 5
5 == 5
3! = 4
5=5
10000
100000
1e2
1 * 10^2
x <- c(1,2,3.14)
x
x <- c(1,2,3,"4214")
x
mode(x)
class(x)
str(x)
x <- c(1,2,3,4)
mode(x)
class(x)
str(x)
x <- c(1,2,3,c(4,5,6))
x
x <- c(90,80,70)
names(x) <- c("국어","영어","수학") 
x[1]
x[3]
x[1:2]
x[-1]
x[c(1,3)]
x['국어']
x["국어"]
x[c("수학","영어")]
length(x)
nrow(x)
NROW(x)
c(1,2,3,4,5)
c(1:100)
x <- c(1:10000)
x
x <- c(1:100)
x
x <- c(1:100)
x
seq(1, 5, 1)
seq(1, 100, 4)
1:10
10:1
seq_along(5)
seq_along(4)
seq_along(2)
seq_along(10)
seq_along(1,2)
seq_along(5)
seq_along(51.2)
seq_along(10)
seq_along(x)
1:NROW(x)
x<-c("a","b")

rep(1:5, times=2)
rep(1:5 , each = 2)
NROW(x)
rep(1:5, times=2 , each=2)
rep(1:5, each=2 , times=2)
x <- c(1:5)
x[2] <- 8
x[3:5] <- c(5,3,9)
x
x[6] <- 60
x[8] <- 80
x <- c(1:10)
x <- append(x, 90, after=8)
x
x <- append(x, 90, after=8)
x
x <- append(x, 100, after=8)
x
x <- c(1,2,3,4,5)
x+10
x
x*10
x
x-10
x
x/2
x
x <-(1,2,3)
y <- (1,2,3)
x == y
x <- c(1,2,3)
y <- c(1,6,5)
x == y
identical(x,y) :두 벡터 값이 동일한지 판단
z <- c(1,2,4)
identical(x,z)
w <- c(1,2,3,3)
identical(x,w)
identical(x,y)
z <- c(1,2,4)
identical(x,z)
w <- c(1,2,3,3)
identical(x,w)
setequal(x,w)
w <- c(1,2,3,3,1)
setequal(x,w)
x == w
x<-c(1,2,3,4)
x ==w
x==x
w<-c(1,2,3,3)
x==w
union(x,y)
intersect(x,y)
setdiff(x,y) 
4 %in% x
1 %in% x
100 %in% x



```
```{r}
x <- c(1,3,5,7,9)
y<-c(1,2,3,4,5)

u<- union(x,y)

i<- intersect(x,y)
i

m <- setdiff(x,y)
m

identical(x,y)
setequal(x,y)

x <- x *10
x

x[x==50]<- 5 
x


```
[문제1] x변수에 1,3,5,7,9 값을 입력, y 변수에 1,2,3,4,5 값을 입력하세요.

x <- c(1,3,5,7,9)
y<-c(1,2,3,4,5)

[문제2] x 변수와 y 변수를 중복성 없이 하나로 합친후에 u 변수에 넣어 주세요.

u<- union(x,y)

[문제3] x 변수와 y 변수의 값들중에 중복성만 추출해서 i 변수에 넣어주세요.

i<- intersect(x,y)

[문제4] x 변수의 값과 y 변수의 값중에 순수하게 x 변수에 들어 있는 값만 추출해서 m 변수에 넣어 주세요.

m <- setdiff(x,y)

[문제5] x 변수의 값과 y 변수의 값이 일치가 되면 TRUE 아니면 FALSE를 출력해주세요.

identical(x,y)
setequal(x,y)

[문제6] x 변수에 값들을 10을 곱한 결과를 x 변수에 적용하세요.

x <- x *10

[문제7] x 변수에 있는 50을 5로 수정하세요.

x[x==50]<- 5 
x

[문제8]  x 변수에 있는 10 30  5 70 90을  원래의 값으로 1,3,5,7,9로 되돌려 주세요.단 union, 정수 나누기, sort 만 사용하세요


[문제9] x변수에 11숫자를 제일 뒤에 입력하세요. 단 append와 length를 이용하세요.
[문제10] x 변수에 제일 뒤에 있는 값을 NA로 수정하세요. 단 length를 이용하세요.
[문제1] x변수에 1,3,5,7,9 값을 입력, y 변수에 1,2,3,4,5 값을 입력하세요.
```{r}


x



x <- c(1,3,5,7,9)
x <- x * 10
x[3] <- 5
x
x <- append(x, 11, length(x))
x
x[length(x)] <- NA
x
x2 <- x
x <- x/10
x2
x
x <- x2
x <- x[1,2,4,5] / 10
x <- x[1:2] /10
x <- x[4:5] /10
x
x <-x2
x
x<- c(10,30,5,70,90)
x
x2 <x
x2<-x
x2
x
x <- x[c(10,30,70,90)] /10
x
x <-x2
x <- x[1,2,4,5,
]
x <- x[1,2,4,5] /10
x <- x[1]/10
x
x <-x2
u <- sort(union(x,y), decreasing = T)
u <- sort(union(x,y))
u
u <- sort(union(x,y), decreasing = TURE)
x
x <- sort(union(x[-3] %/% 10, x[3]))
x
help?apennd
help(appennd)
help(append)
help(append)
x <- list(name = '홍길동', addr = '서울' , pn = '010-1111-0000')
x$name
x$addr
x$pn
x <-1
x
x <- list(name = '홍길동', addr = '서울' , pn = '010-1111-0000')
x$name
x$addr
x$pn
x[1]
x[2]
x[3]
x[[1]]
x[1:2]
x <- list( a = list(val = c(1,2,3)), b = list(val = c(1,2,3,4)))
x
x$a
x$b
q()
lst <- list(name = c("king"), height = c(180), weight = c(70))
lst
lst$blood <- "A"
lst
lst$name <- "scott"
lst
lst[2]
lst$blood<- last$blood type
lst$blood <- lst$blood type
lst$blood type <- lst$blood
lst <- list(name = c("king"), height = c(180), weight = c(70), blood type = c("A"))
lst$blood<- last$blood type
lst$sal <-10000
lst
lst$sal <- NULL
lst
lst$blood type <-c(lst$blood)
names(lst)
names(lst)[4]
names(lst)[4] <- "blood type"
lst
names(lst) <- NULL
lst
names(lst) <- c(name, height, weight, blood type)
names(lst) <- c('name', 'height', 'weight', 'blood type')
lst
q()

```
[문제16] x 변수에 벡터값 1,2,3,5,6 을 입력한 후 3번째 요소 뒤에 4를 입력하세요.
x<- c(1,2,3,5,6)
x<- append(x,4,after=3)
x

[문제17] 1부터  3씩 증가하는 10 이하의 정수값을 출력하세요.
x<- seq(1,10,by=3)
x

[문제18] 10 부터 20 까지의 값을 x 변수에 생성한 후 원소의 값이 15 이상이고 18 이하인 값들만 출력하세요.
x<-c(10:20)
x>= 15 & x <=18
x[x>= 15 & x <=18]  #안에들어간 데이터의 값이 트루인 값만 출력

[문제19] 10 부터 20 까지의 값을 x 변수에 생성한 후 원소의 값이 15 이상이고 18 이하인 값들만 2곱한 값으로 수정하세요.
x <- x[x>= 15 & x <=18]*2
x

벡터란? 1차원 배열 
리스트란? 서로다른 타입의 데이터를 저장하기위한 방법
seq(1,10,length.out=5) #length.out = 생성할 벡터의 갯수, 균일한 증가분으로 1~10사이에 5개의 숫자를 만들고 싶을 때.


